### ISSUE TITLE
cant open 3DS controller.exe on the pc (windows 10)

### ISSUE THREAD

**Issue by Joutenheim** [CTurt/3DSController#7]
first error: "libgcc_s_dw2-1.dll is missing from your computer..."
-i got the dll file then i tried putting the missing dll in the same folder as the 3DSController.exe file, then:

second error: "libstdc++-6.dll is missing from your computer..."
-did the same as before; got the .dll then i placed it in the same folder as 3DSController.exe, then:

third error: "the application couldn't start correctly (0xc000007b)."

after the last error, i cant think of any other way on how to make it work, tried changing compatibility option, still didnt work. i wonder if its the .dll files that i got, but not sure, i dont know much about this stuff xD

im running on windows 10

any help?

**Comment by chickenmatt5** [comment]
Also having this issue. It appears both those files have something to do with software called MinGW, although installing it doesn't solve any problems. Would love a fix for these errors.

**Comment by CTurt** [comment]
Windows 10 and DLL errors fixed

**Comment by Akawashi** [comment]
Also having this issue with Windows 7 x64. i had no issues on win 10 x32 (on this same machine, i recently re-installed win 7 x64) 
The Error Starts with refusing to work because "MSVCR120.dll is missing from your computer" (It's not, it's hiding in C\Windows\System32) Even so, I copy it to the 3DSController Folder (PC) and try to run  the 3DScontroller.exe  and i get a New Error : "The Application was unable to start correctly (0xc000007b)." (<- This is apparently to do with bits, maybe your program has issues on a x64 bit OS? it worked fine for me on x32 win 10.) i have searched high and low, but i STILL can't find a fix for this error.
I've ran it as Admin, 
I've Re-installed DirectX to Latest Version. (DX11) 
  "          "            .Net Framework.
  "          "            Visual Baisic, Python  and Microsoft C++.
I've Tried replacing DLLs in the system32 & sysWOW folders in safe mode.
I've tried restarting my computer.
I've Tried DSKCHK.
The only think i havn't tried is Reinstalling/restoring Windows.. and i don't really want to have to do that without trying EVERYTHING else first... and, asking the creater of the Program seemed the next best step. Please help me, i'm SURE i'm not the only one facing this issue.
My E-Mail is Kosovokid21@gmail.com. I am Akawashi on That Chaos Site, That Temp Site and That Iso Site. I'm a HUGE fan of your work, and once i finally get this working, i can use my 3ds to play on RetroArch on my pc :)

**Comment by Akawashi** [comment]
UPDATE: I had an idea and it worked. 
I have the x64 version of MSVCR120.dll (as i should) 
Your 3DSController was asking for MSVCR120.dll
I gave it MY MSVCR120.dll
It Didn't Work.
I've just told you i think it could be your program not working well on x64 OS, and it got me thinking.
Please go Here: https://www.dll-files.com/msvcr120.dll.html and download the x32 version at the bottom of the page. add it to your 3dscontroller's PC folder (so that it's with 3dscontroller.exe) Please include that file with your download. This has just FIXED the issue on x64 bit Operating Systems. 
Sorry for being a Rambler, but i fixed the issue i had, now i hope you can pass on the good news :)
Yes, it needs MSVCR120.dll.... But it doesn't specify if it needs x32 or x64 (It needs x32, in the same folder as 3dscontroller.exe in order to function)

**Comment by arynadam** [comment]
Alternative download link http://www.dll4free.com/msvcr120.dll.html
